---
title: "Plot map"
author: "Jonathan Rystrøm"
date: '2022-05-23'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
pacman::p_load(tidyverse, tmap, sf, ggmap)
```

```{r}
rawdat <- read_csv("out/gas_distances.csv")
```

```{r}
colors <- c("#91CF60", "#FC8D59", "#800026")
dat <- rawdat %>% 
  st_as_sf(coords=c("long", "lat"), crs=4326) %>% 
  mutate(dist_cats = case_when(
    distance < 500 ~ "Under 500m", 
    between(distance, 500, 1000) ~ "Between 500m & 1000m", 
    distance > 1000 ~ "Over 1000m"
  )) %>% 
  mutate(dist_colors = case_when(
    distance < 500 ~ colors[1], 
    between(distance, 500, 1000) ~ colors[2], 
    distance > 1000 ~ colors[3]
    ))


dk_border <- raster::getData("GADM", country = "DNK", level = 0)
```
## Histogram
```{r histogram}
ggplot(dat, aes(x=distance, fill=dist_cats)) + 
  geom_histogram(bins=100) + 
  scale_x_log10() + 
  theme_minimal() + 
  scale_fill_manual(values=c(colors[2], colors[3], colors[1])) + 
  labs(title = "Distance from Gas-heated Buildings to the Fjernvarme Network", subtitle = "Data Source: BBR", fill = NULL, x="Distance to Fjernvarme Network")


```



### plot denmark
```{r}
small_dat <- dat %>% 
  sample_n(1000)


sf::st_crs(dk_border) == sf::st_crs(small_dat)
tmap::tmap_mode("plot")

gas_map <- tm_shape(dk_border) + 
  tm_polygons(col="white")  + 
tm_shape(dat) +
  tm_dots(size=0.03, col="dist_colors", alpha=0.3) + 
  tm_add_legend(type="fill", col = colors, labels = c("mindre end 500m", "mellem 500m og 1km", "mere end 1km"), title="Afstand til fjernvarmenet")

#gas_map

tmap_save(gas_map, filename = "gas_fjernvarme_afstand.png", width=1920, height=1080)

```

```{r}
pacman::p_load(tidyverse)
load(file="polling.rda")


polling %>% 
  head()

polling %>% 
  janitor::clean_names() %>% 
  filter(id == "1sundbyvester") 

polling %>% 
  distinct() %>% 
  arrange(id)

polling %>% 
  filter(str_detect(group, "agersted")) %>% 
  distinct(group)

polling %>% 
  mutate(strlen = str_length(AfstemKod)) %>% 
  summarise(max(strlen))

polling %>% 
  # KAEFT DET BLIVER GODT --> her er join kode
  filter(KommuneNum == "860" & AfstemKod == "28")
```

